name = "mumu"
version = "1.0.2"

description = "Hash strings using the non-cryptographic hash Murmur3 in Gleam"
licences = ["MIT"]
repository = { type = "github", user = "georgesboris", repo = "mumu" }
links = []

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
harness_erlang_murmurhash = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
